### ISSUE TITLE
for_each error thrown from "fhir_store_iam_members"

### ISSUE THREAD

**Issue by yeweidaniel** [terraform-google-modules/terraform-google-healthcare#34]
When running `terraform plan` on the Terraform Engine (tfengine) generated scripts, I am getting the following error:

> Error: Invalid for_each argument
> 
>   on .terraform/modules/test_healthcare_dataset/iam.tf line 68, in resource "google_healthcare_fhir_store_iam_member" "fhir_store_iam_members":
>   68:   for_each = {
>   69:     for m in local.all_fhir_iam_members :
>   70:     "${m.store_name} ${m.role} ${m.member}" => m
>   71:   }
> 
> The "for_each" value depends on resource attributes that cannot be determined
> until apply, so Terraform cannot predict how many instances will be created.
> To work around this, use the -target argument to first apply only the
> resources that the for_each depends on.

In the original hcl file used by Terraform Engine, the FHIR stores are defined as follows:

```
      healthcare_datasets = [{
        name = "{{.prefix}}-{{.env}}-healthcare-dataset"
        fhir_stores = [{
          name = "intermediate-fhir-store"
          version = "R4"
          enable_update_create = true
          disable_referential_integrity = true
          notification_config = {
            pubsub_topic = "projects/{{$.prefix}}-{{$.env}}-pipeline/topics/$${module.{{.prefix}}_{{.env}}_intermediate_store_topic.id}"
          }
        },
        {
          name = "final-fhir-store"
          version = "R4"
          enable_update_create = true
          disable_referential_integrity = true
        }]
      }]
```

The script uses this healthcare module, happy to move the issue to Terraform Engine's repository if that's more appropriate.

**Comment by umairidris** [comment]
This is a limitation in terraform due to use of type 'any'. You will need to define the same set of fields for all fhir stores, even if some of them are using default values.

**Comment by umairidris** [comment]
Though I do wonder why you are getting error on the iam members resource when none are being set.. Can you generate the output and send the exact healthcare dataset block so we can reproduce that on the module?

**Comment by xingao267** [comment]
The following config would reproduce the error:

```
module "healthcare_dataset" {
  source  = "terraform-google-modules/healthcare/google"
  version = "~> 1.2.0"

  name     = "healthcare-dataset"
  project  = module.project.project_id
  location = "us-east1"

  fhir_stores = [
    {
      name    = "intermediate-fhir-store"
      version = "R4"

      enable_update_create          = true
      disable_referential_integrity = true
      notification_config = {
        pubsub_topic = "projects/xingao-dev-1221/topics/${module.intermediate_store_topic.id}"
      }
    },
  ]
}

module "intermediate_store_topic" {
  source  = "terraform-google-modules/pubsub/google"
  version = "~> 1.7.0"

  topic      = "intermediate-store-topic"
  project_id = module.project.project_id

  pull_subscriptions = [
    {
      name = "intermediate-store-subscription"
    },
  ]

  depends_on = [
    module.project
  ]
}
```

For some reason, having the dynamic calculated pubsub topic id there would affect the iam_member resource.

**Comment by yeweidaniel** [comment]
The generated healthcare dataset block is:

```
module "test1_healthcare_dataset" {
  source  = "terraform-google-modules/healthcare/google"
  version = "~> 1.2.0"

  name     = "test1-healthcare-dataset"
  project  = module.project.project_id
  location = "us-central1"

  fhir_stores = [
    {
      name    = "intermediate-fhir-store"
      version = "R4"

      enable_update_create          = true
      disable_referential_integrity = true
      notification_config = {
        pubsub_topic = "projects/test1-pipeline/topics/${module.test1_intermediate_store_topic.id}"
      }
    },
    {
      name    = "final-fhir-store"
      version = "R4"

      enable_update_create          = true
      disable_referential_integrity = true
    },
  ]
}
```

**Comment by xingao267** [comment]
Found one workaround which you can change `pubsub_topic = "projects/test1-pipeline/topics/${module.test1_intermediate_store_topic.id}"` to `pubsub_topic = "projects/test1-pipeline/topics/${module.test1_intermediate_store_topic.*topic*}"`. `topic` value here is not dynamically calculated.

**Comment by yeweidaniel** [comment]
Using `topic` works, thank you both for looking into it! Closing the issue now.

**Comment by xingao267** [comment]
Created https://github.com/terraform-google-modules/terraform-google-healthcare/issues/35 to keep track of the underlying issue.
