### ISSUE TITLE
Not able to upgrade terraform version to >= 0.13

### ISSUE THREAD

**Issue by chaopeng** [terraform-google-modules/terraform-google-healthcare#38]
See: https://github.com/terraform-google-modules/terraform-google-healthcare/pull/37

Also tried to both upgrade terraform and google-provider https://github.com/terraform-google-modules/terraform-google-healthcare/pull/36

Any idea?

**Comment by xingao267** [comment]
I'm looking into the underlying Terraform provider issue.

**Comment by xingao267** [comment]
The provider with the fix has been released in 3.54.0.
