### ISSUE TITLE
Dicom StreamConfigs

### ISSUE THREAD

**Issue by khuong507** [terraform-google-modules/terraform-google-healthcare#44]
Please add support for StreamConfigs on the dicom store as specified here:
https://cloud.google.com/healthcare/docs/how-tos/dicom-bigquery-streaming

A similar change was done here: 
https://github.com/terraform-google-modules/terraform-google-healthcare/pull/22/files

**Comment by xingao267** [comment]
DICOM stream configs is not in the Terraform provider yet. Opened https://github.com/hashicorp/terraform-provider-google/issues/8609 to track.

**Comment by manjunathbellad** [comment]
Hello ,

Is it possible to expedite this request. We need this feature for a prod release by this month's end .
